### ISSUE TITLE
[INIT] CI/CD 세팅

### ISSUE THREAD

**Issue by seokbeom00** [Roots-and-Fruits/RootsAndFruitsDeliveryServer#1]
## 🛠 Issue
* 프로젝트 초기 CI/CD 세팅

## 📝 To-do
- [x] 도커 허브 계정 생성
- [x] dockerfile 및 배포 파일 세팅
- [x] nginx 세팅
- [x] deploy.sh 세팅
